generated_hydrator:
    class_namespace: App\Hydrator
    target_directory: "%kernel.project_dir%/hydrator"

    # For nested objects/deep graph hydrator, set property classes to
    # ignore for which generated hydration should not be attempted.
    class_blacklist:
        - App\SomeClass
        - DateTime
        - DateTimeImmutable
        - DateTimeInterface
        - Ramsey\Uuid\Uuid
        - Ramsey\Uuid\UuidInterface

    # Set here an array of fully qualifiied PHP class names which
    # you wish the generate command to be able to pre-generate.
    # If you leave this empty, hydrator generation will always be
    # lazy and at runtime.
    class_list: []
