parameters:
    generated_hydrator.class_list: []

services:

    generated_hydrator.value_hydrator_registry:
        class: GeneratedHydrator\Bridge\Symfony\ValueHydrator\ValueHydratorRegistry
        arguments: [[]] # Populated by a compiler pass.

    generated_hydrator.hydration_plan_builder.reflection:
        public: false
        class: GeneratedHydrator\Bridge\Symfony\HydrationPlan\ReflectionHydrationPlanBuilder
    generated_hydrator.hydration_plan_builder.default:
        alias: generated_hydrator.hydration_plan_builder.reflection

    # Hydration builder cache (hides the default one)
    generated_hydrator.hydration_plan_builder.cache:
        public: false
        class: GeneratedHydrator\Bridge\Symfony\HydrationPlan\CachedHydrationPlanBuilder
        arguments: ['@generated_hydrator.hydration_plan_builder.default', '@cache.app']

    # Facade for hydration plan builder (holds the cached implementation)
    generated_hydrator.hydration_plan_builder:
        public: false
        alias: generated_hydrator.hydration_plan_builder.cache

    generated_hydrator.class_black_list:
        public: false
        class: GeneratedHydrator\Bridge\Symfony\ClassBlacklist

    generated_hydrator.default:
        public: false
        class: GeneratedHydrator\Bridge\Symfony\DefaultHydrator
        arguments: ["%kernel.cache_dir%/hydrator"]
    generated_hydrator.deep:
        public: false
        class: GeneratedHydrator\Bridge\Symfony\DeepHydrator
        arguments:
            - "@generated_hydrator.default"
            - "@generated_hydrator.hydration_plan_builder"
            - "@generated_hydrator.class_black_list"
            - "@generated_hydrator.value_hydrator_registry"
    generated_hydrator:
        alias: generated_hydrator.deep
    GeneratedHydrator\Bridge\Symfony\DeepHydrator:
        alias: generated_hydrator.deep
    GeneratedHydrator\Bridge\Symfony\Hydrator:
        alias: generated_hydrator

    generated_hydrator.command.generate:
        public: false
        class: GeneratedHydrator\Bridge\Symfony\Command\GenerateCommand
        arguments: ['@generated_hydrator.default', "%generated_hydrator.class_list%"]
        tags: ['console.command']
